# Generated by Django 2.1.7 on 2019-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_auto_20190228_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_delete_perrmission',
            field=models.BooleanField(default=False),
        ),
    ]
