# Generated by Django 2.1.7 on 2019-03-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_article_update_delete_perrmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_delete_perrmission',
        ),
    ]
