# Generated by Django 2.1.7 on 2019-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_remove_article_update_delete_perrmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='Article content'),
        ),
    ]
