# Generated by Django 2.1.7 on 2019-02-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(blank=True, max_length=100, verbose_name='User interests')),
                ('photo', models.ImageField(blank=True, default='../static/img/images.png', upload_to='images/user_pics', verbose_name='User Photo')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='User Registration Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
